name: lint

on:
  # trigger on pushes to any branch, but not main
  push:
    branches-ignore:
      - main
  # and also on PRs to main
  pull_request:
    branches:
      - main

jobs:
  pre-commit-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - uses: pre-commit/action@v2.0.3
